#!/usr/bin/env python3
"""
qualimap_ai.py -- parse Qualimap reports and add AI summaries via an OpenAI-compatible endpoint.

Discovers and annotates:
  1) Multi-sample BAM QC report (multisampleBamQcReport.html)
  2) Single-sample RNA-Seq QC reports (qualimapReport.html in rnaseqqc_results)
  3) Single-sample BAM QC reports (qualimapReport.html in bamqc_results)

The LLM is any OpenAI-compatible /v1/chat/completions endpoint (local vLLM, Ollama,
OpenAI, etc.). No endpoint or model is baked in -- you must supply them at runtime
via CLI flags or env vars (LLM_ENDPOINT, LLM_MODEL, LLM_API_KEY).
"""

import argparse
import os
import re
import sys
import time
from html.parser import HTMLParser

# Import shared LLM module
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import llm_common

# Config defaults (CLI flag > env var > fallback)
DEF_ENDPOINT       = os.environ.get("LLM_ENDPOINT")
DEF_MODEL          = os.environ.get("LLM_MODEL")
DEF_API_KEY        = os.environ.get("LLM_API_KEY", "dummy")
DEF_CONTEXT_WINDOW = int(os.environ.get("LLM_CONTEXT_WINDOW", "128000"))
DEF_TIMEOUT        = int(os.environ.get("LLM_TIMEOUT", "300"))

SYS_PROMPT_MULTISAMPLE = "\n".join([
    "You are an expert bioinformatician evaluating a Qualimap Multi-sample BAM QC report for an RNA-Seq experiment.",
    "Produce 2-4 concise bullet points summarizing key quality metrics across samples.",
    "Assess coverage depth, GC content, mapping quality, and identify any clear outlier samples.",
    "Use markdown. Highlight severity with directives like :span[value]{.text-red}, .text-orange, .text-yellow, .text-green.",
    "Highlight sample names with :sample[GSM12345]{.text-red} etc.",
    "If all samples pass quality standards and look uniform, explicitly state so.",
])

SYS_PROMPT_RNASEQ = "\n".join([
    "You are an expert bioinformatician evaluating a Qualimap RNA-Seq QC report for a single sample.",
    "Produce 2-3 concise bullet points summarizing key observations.",
    "Cover: total mapped reads & mapping rate, genomic origin breakdown (Exonic vs Intronic/Intergenic %), and 5'-3' transcript coverage bias.",
    "Highlight severity with directives like :span[value]{.text-red}, .text-orange, .text-yellow, .text-green.",
    "Highlight sample names with :sample[name]{.text-red} etc.",
    "State clearly if quality is satisfactory or if there are contamination/degradation flags.",
])

SYS_PROMPT_BAMQC = "\n".join([
    "You are an expert bioinformatician evaluating a Qualimap BAM QC report for a single sample.",
    "Produce 2-3 concise bullet points summarizing key alignment quality metrics (mapping rate, duplication rate, mean coverage, mapping quality).",
    "Highlight severity with directives like :span[value]{.text-red}, .text-orange, .text-yellow, .text-green.",
    "Highlight sample names with :sample[name]{.text-red} etc.",
    "State clearly if quality is satisfactory or if there are flags.",
])

AI_TIMEOUT_MSG = "ai_insights timeout. Please try again"

def ai_footer(cfg, usage, data_filename=None):
    secs = float(usage.get("duration_s", 0.0) or 0.0)
    toks = llm_common.answer_tokens(usage)
    tps = (toks / secs) if secs > 0 else 0.0
    stamp = time.strftime("%Y-%m-%d %H:%M UTC", time.gmtime())
    table_str = f" — Table parsed: {os.path.basename(data_filename)}" if data_filename else ""
    return (f'<div class="text-muted" style="font-size:.85em;margin-top:8px;'
            f'border-top:1px solid #eee;padding-top:4px;color:#6c757d;">'
            f'🤖 AI summary — Automatic interpretation by an LLM; always verify '
            f'against the data — Generated by {cfg.llm_model} on {stamp}, '
            f'{tps:.0f} TPS, {secs:.0f} seconds{table_str}</div>')

def style_directives(txt):
    # Convert markdown bold (**text** or __text__) to <strong>
    txt = re.sub(r"\*\*(.*?)\*\*", r"<strong>\1</strong>", txt)
    txt = re.sub(r"__(.*?)__", r"<strong>\1</strong>", txt)
    # Convert markdown italic (*text*) to <em>
    txt = re.sub(r"(?<!\*)\*(?!\*)(.*?)(?<!\*)\*(?!\*)", r"<em>\1</em>", txt)
    # Convert inline code (`text`) to <code>
    txt = re.sub(r"`([^`]+)`", r"<code>\1</code>", txt)

    colors = {
        "red": "color:#d9534f;font-weight:600;",
        "orange": "color:#f0ad4e;font-weight:600;",
        "yellow": "color:#b8860b;font-weight:600;",
        "green": "color:#5cb85c;font-weight:600;"
    }
    for sev, css in colors.items():
        txt = re.sub(rf":span\[([^\]]*)\]\{{\.text-{sev}\}}", rf'<span style="{css}">\1</span>', txt)
        txt = re.sub(rf":sample\[([^\]]*)\]\{{\.text-{sev}\}}",
                     rf'<span style="{css}font-style:italic;">\1</span>', txt)
    txt = re.sub(r":span\[([^\]]*)\]\{[^}]*\}", r"\1", txt)
    txt = re.sub(r":sample\[([^\]]*)\]\{[^}]*\}",
                 r'<span style="font-weight:600;font-style:italic;">\1</span>', txt)
    return txt

def md_to_html(txt):
    txt = style_directives(txt)
    out, depth = [], 0
    for line in txt.split("\n"):
        indent = len(line) - len(line.lstrip())
        t = line.strip()
        m = re.match(r"[-*] (.*)", t)
        if m:
            target = indent // 4 + 1
            while depth < target: out.append("<ul style='margin-top:4px;margin-bottom:4px;'>"); depth += 1
            while depth > target: out.append("</ul>"); depth -= 1
            out.append(f"<li>{m.group(1)}</li>")
        elif t:
            while depth > 0: out.append("</ul>"); depth -= 1
            out.append(f"<p style='margin-top:4px;margin-bottom:4px;'>{t}</p>")
    while depth > 0: out.append("</ul>"); depth -= 1
    return "\n".join(out)

# HTML Table Parser Helper
class HTMLTableTextExtractor(HTMLParser):
    def __init__(self):
        super().__init__()
        self.in_table = False
        self.in_cell = False
        self.current_table = []
        self.current_row = []
        self.current_cell = []
        self.tables = []

    def handle_starttag(self, tag, attrs):
        if tag == "table":
            self.in_table = True
            self.current_table = []
        elif tag in ("td", "th") and self.in_table:
            self.in_cell = True
            self.current_cell = []
        elif tag == "tr" and self.in_table:
            self.current_row = []

    def handle_endtag(self, tag):
        if tag == "table" and self.in_table:
            self.in_table = False
            if self.current_table:
                self.tables.append(self.current_table)
        elif tag in ("td", "th") and self.in_cell:
            self.in_cell = False
            self.current_row.append(" ".join("".join(self.current_cell).split()))
        elif tag == "tr" and self.in_table:
            if self.current_row:
                self.current_table.append(self.current_row)

    def handle_data(self, data):
        if self.in_cell:
            self.current_cell.append(data)

def extract_tables_as_text(html_content):
    parser = HTMLTableTextExtractor()
    parser.feed(html_content)
    lines = []
    for idx, table in enumerate(parser.tables):
        for row in table:
            lines.append("\t".join(row))
        lines.append("")
    return "\n".join(lines)

def parse_multisample_html(html_path):
    with open(html_path, encoding="utf-8", errors="replace") as fh:
        content = fh.read()
    table_text = extract_tables_as_text(content)
    return content, table_text

def parse_rnaseq_qc(report_dir, html_path):
    txt_path = os.path.join(report_dir, "rnaseq_qc_results.txt")
    if os.path.exists(txt_path):
        with open(txt_path, encoding="utf-8", errors="replace") as fh:
            text_data = fh.read()
    else:
        with open(html_path, encoding="utf-8", errors="replace") as fh:
            text_data = extract_tables_as_text(fh.read())
    with open(html_path, encoding="utf-8", errors="replace") as fh:
        html_content = fh.read()
    return html_content, text_data

def parse_bam_qc(report_dir, html_path):
    txt_path = os.path.join(report_dir, "genome_results.txt")
    if os.path.exists(txt_path):
        with open(txt_path, encoding="utf-8", errors="replace") as fh:
            text_data = fh.read()
    else:
        with open(html_path, encoding="utf-8", errors="replace") as fh:
            text_data = extract_tables_as_text(fh.read())
    with open(html_path, encoding="utf-8", errors="replace") as fh:
        html_content = fh.read()
    return html_content, text_data

def inject_ai_box(html_content, summary_body_html, footer_html):
    box_html = (
        f'\n<div class="ai-summary-box" style="background-color: #f8f9fa; border-left: 4px solid #007bff; '
        f'padding: 12px 16px; margin: 15px 0; border-radius: 4px; font-family: sans-serif;">\n'
        f'  <h4 style="margin-top:0; margin-bottom: 8px; color: #007bff; font-weight: 600;">🤖 AI Summary</h4>\n'
        f'  <div class="ai-summary-content" style="font-size: 0.95em; color: #333;">\n{summary_body_html}\n  </div>\n'
        f'  {footer_html}\n'
        f'</div>\n'
    )

    # Check if already injected
    if 'class="ai-summary-box"' in html_content:
        return html_content

    # Inject right after Summary heading div or section
    pattern = r'(<h2[^>]*>\s*Summary\s*<.*?</h2>)'
    if re.search(pattern, html_content, re.IGNORECASE):
        return re.sub(pattern, r'\1' + box_html, html_content, count=1, flags=re.IGNORECASE)

    # Fallback 1: right after <div class="content">
    if '<div class="content">' in html_content:
        return html_content.replace('<div class="content">', '<div class="content">' + box_html, 1)

    return html_content + box_html

def ask_llm(cfg, sys_prompt, data_text):
    data_text = llm_common.cap_text(data_text, cfg.llm_context_window)
    messages = [
        {"role": "system", "content": sys_prompt},
        {"role": "user",   "content": f"Data:\n{data_text}"},
    ]
    try:
        text, usage = llm_common.chat_completion(
            cfg.llm_endpoint, cfg.llm_model, cfg.llm_api_key, messages, timeout=cfg.llm_timeout)
    except llm_common.LLMTimeout:
        raise
    except Exception as e:
        print(f"[AI] Qualimap error: {e}", flush=True)
        return "_(no AI response)_", {}
    return (text or "_(no AI response)_"), usage

def process_multisample_report(cfg, html_path):
    print(f"[Qualimap AI] Annotating multi-sample report: {html_path}", flush=True)
    html_content, table_text = parse_multisample_html(html_path)
    if not table_text.strip():
        print(f"[Qualimap AI] Warning: No table data found in {html_path}", flush=True)
        return

    text, usage = ask_llm(cfg, SYS_PROMPT_MULTISAMPLE, table_text)
    if llm_common.is_degraded(text):
        print(f"[Qualimap AI] Degraded response dropped for {html_path}", flush=True)
        return

    summary_html = md_to_html(text)
    footer = ai_footer(cfg, usage, data_filename="multibamqc_results")
    new_html = inject_ai_box(html_content, summary_html, footer)

    with open(html_path, "w", encoding="utf-8") as fh:
        fh.write(new_html)
    print(f"[Qualimap AI] Done multi-sample report: {html_path}", flush=True)

def process_single_sample_report(cfg, html_path, report_type):
    report_dir = os.path.dirname(html_path)
    sample_name = os.path.basename(report_dir)
    print(f"[Qualimap AI] Annotating {report_type} report for {sample_name}: {html_path}", flush=True)

    if report_type == "rnaseq":
        html_content, text_data = parse_rnaseq_qc(report_dir, html_path)
        sys_prompt = SYS_PROMPT_RNASEQ
        parsed_name = "rnaseq_qc_results.txt"
    else:
        html_content, text_data = parse_bam_qc(report_dir, html_path)
        sys_prompt = SYS_PROMPT_BAMQC
        parsed_name = "genome_results.txt"

    if not text_data.strip():
        print(f"[Qualimap AI] Warning: No text data for {sample_name}", flush=True)
        return

    text, usage = ask_llm(cfg, sys_prompt, text_data)
    if llm_common.is_degraded(text):
        print(f"[Qualimap AI] Degraded response dropped for {sample_name}", flush=True)
        return

    summary_html = md_to_html(text)
    footer = ai_footer(cfg, usage, data_filename=parsed_name)
    new_html = inject_ai_box(html_content, summary_html, footer)

    with open(html_path, "w", encoding="utf-8") as fh:
        fh.write(new_html)
    print(f"[Qualimap AI] Done {sample_name}", flush=True)

def main():
    p = argparse.ArgumentParser(description="Qualimap AI annotation script.")
    p.add_argument("--analysis-dir", required=True, help="Root directory containing Qualimap reports.")
    p.add_argument("--llm-endpoint", default=DEF_ENDPOINT, help="OpenAI-compatible URL")
    p.add_argument("--llm-model", default=DEF_MODEL, help="Model name")
    p.add_argument("--llm-api-key", default=DEF_API_KEY, help="API key")
    p.add_argument("--llm-context-window", type=int, default=DEF_CONTEXT_WINDOW)
    p.add_argument("--llm-timeout", type=int, default=DEF_TIMEOUT)
    args = p.parse_args()

    if not args.llm_endpoint or not args.llm_model:
        print("[Qualimap AI] LLM_ENDPOINT and LLM_MODEL must be supplied. Exiting without changes.", flush=True)
        sys.exit(0)

    cfg = args
    analysis_dir = os.path.abspath(args.analysis_dir)

    multi_reports = []
    single_rnaseq_reports = []
    single_bam_reports = []

    for root, dirs, files in os.walk(analysis_dir):
        for f in files:
            full = os.path.join(root, f)
            if f == "multisampleBamQcReport.html":
                multi_reports.append(full)
            elif f == "qualimapReport.html":
                root_low = root.lower()
                if os.path.exists(os.path.join(root, "rnaseq_qc_results.txt")) or "rnaseq" in root_low:
                    single_rnaseq_reports.append(full)
                elif os.path.exists(os.path.join(root, "genome_results.txt")) or "bam" in root_low:
                    single_bam_reports.append(full)
                else:
                    single_rnaseq_reports.append(full)

    secrets = llm_common.secret_values(endpoint=cfg.llm_endpoint, api_key=cfg.llm_api_key)

    try:
        # Process Multi-sample report first
        for m_rep in multi_reports:
            try:
                process_multisample_report(cfg, m_rep)
                llm_common.scrub_file(m_rep, secrets)
            except llm_common.LLMTimeout:
                print(f"[Qualimap AI] Timeout processing {m_rep}", flush=True)

        # Process single-sample RNA-Seq reports
        for r_rep in single_rnaseq_reports:
            try:
                process_single_sample_report(cfg, r_rep, "rnaseq")
                llm_common.scrub_file(r_rep, secrets)
            except llm_common.LLMTimeout:
                print(f"[Qualimap AI] Timeout processing {r_rep}", flush=True)

        # Process single-sample BAM reports
        for b_rep in single_bam_reports:
            try:
                process_single_sample_report(cfg, b_rep, "bamqc")
                llm_common.scrub_file(b_rep, secrets)
            except llm_common.LLMTimeout:
                print(f"[Qualimap AI] Timeout processing {b_rep}", flush=True)

    except Exception as e:
        print(f"[Qualimap AI] Error during AI pass: {e}", flush=True)

if __name__ == "__main__":
    main()
