#!/usr/bin/env python3
"""
qualimap_ai.py -- parse Qualimap reports and add AI summaries via an OpenAI-compatible endpoint.

Discovers and annotates:
  1) Multi-sample BAM QC report (multisampleBamQcReport.html)
  2) Single-sample RNA-Seq QC reports (qualimapReport.html in rnaseqqc_results)
  3) Single-sample BAM QC reports (qualimapReport.html in bamqc_results)

The LLM is any OpenAI-compatible /v1/chat/completions endpoint (local vLLM, Ollama,
OpenAI, etc.). No endpoint or model is baked in -- you must supply them at runtime
via CLI flags or env vars (LLM_ENDPOINT, LLM_MODEL, LLM_API_KEY).
"""

import argparse
import os
import re
import sys
import time
from html.parser import HTMLParser

# Import shared LLM module
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import llm_common

# Config defaults (CLI flag > env var > fallback)
DEF_ENDPOINT       = os.environ.get("LLM_ENDPOINT")
DEF_MODEL          = os.environ.get("LLM_MODEL")
DEF_API_KEY        = os.environ.get("LLM_API_KEY", "dummy")
DEF_CONTEXT_WINDOW = int(os.environ.get("LLM_CONTEXT_WINDOW", "128000"))
DEF_TIMEOUT        = int(os.environ.get("LLM_TIMEOUT", "300"))

SYS_PROMPT_MULTISAMPLE = (
    "You are an expert bioinformatician evaluating a Qualimap Multi-sample BAM QC report for an RNA-Seq experiment.\n"
    "Produce 2-4 concise bullet points summarizing key quality metrics across samples.\n"
    "Assess coverage depth, GC content, mapping quality, and identify any clear outlier samples.\n"
    "Use standard plain markdown list items (- bullet point).\n"
    "If all samples pass quality standards and look uniform, explicitly state so."
)

SYS_PROMPT_RNASEQ = (
    "You are an expert bioinformatician evaluating a Qualimap RNA-Seq QC report for a single sample.\n"
    "Produce 2-3 concise bullet points summarizing key observations.\n"
    "Cover total mapped reads & mapping rate, genomic origin breakdown (Exonic vs Intronic/Intergenic %), and 5'-3' transcript coverage bias.\n"
    "Use standard plain markdown list items (- bullet point).\n"
    "State clearly if quality is satisfactory or if there are contamination/degradation flags."
)

SYS_PROMPT_BAMQC = (
    "You are an expert bioinformatician evaluating a Qualimap BAM QC report for a single sample.\n"
    "Produce 2-3 concise bullet points summarizing key alignment quality metrics (mapping rate, duplication rate, mean coverage, mapping quality).\n"
    "Use standard plain markdown list items (- bullet point).\n"
    "State clearly if quality is satisfactory or if there are flags."
)

AI_TIMEOUT_MSG = "ai_insights timeout. Please try again"

def ai_footer(cfg, usage, data_filename=None):
    secs = float(usage.get("duration_s", 0.0) or 0.0)
    toks = llm_common.answer_tokens(usage)
    tps = (toks / secs) if secs > 0 else 0.0
    stamp = time.strftime("%Y-%m-%d %H:%M UTC", time.gmtime())
    table_str = f" — Table parsed: {os.path.basename(data_filename)}" if data_filename else ""
    return (f'<div class="text-muted" style="font-size:.85em;margin-top:8px;'
            f'border-top:1px solid #eee;padding-top:4px;color:#6c757d;">'
            f'🤖 AI summary — Automatic interpretation by an LLM; MUST always verify '
            f'against the data — Generated by {cfg.llm_model} on {stamp}, '
            f'{tps:.0f} TPS, {secs:.0f} seconds{table_str}</div>')

def style_directives(txt):
    # Convert markdown bold (**text** or __text__) to <strong>
    txt = re.sub(r"\*\*(.*?)\*\*", r"<strong>\1</strong>", txt)
    txt = re.sub(r"__(.*?)__", r"<strong>\1</strong>", txt)
    # Convert markdown italic (*text*) to <em>
    txt = re.sub(r"(?<!\*)\*(?!\*)(.*?)(?<!\*)\*(?!\*)", r"<em>\1</em>", txt)
    # Convert inline code (`text`) to <code>
    txt = re.sub(r"`([^`]+)`", r"<code>\1</code>", txt)

    colors = {
        "red": "color:#d9534f;font-weight:600;",
        "orange": "color:#f0ad4e;font-weight:600;",
        "yellow": "color:#b8860b;font-weight:600;",
        "green": "color:#5cb85c;font-weight:600;"
    }
    for sev, css in colors.items():
        txt = re.sub(rf":span\[([^\]]*)\]\{{\.text-{sev}\}}", rf'<span style="{css}">\1</span>', txt)
        txt = re.sub(rf":sample\[([^\]]*)\]\{{\.text-{sev}\}}",
                     rf'<span style="{css}font-style:italic;">\1</span>', txt)
    txt = re.sub(r":span\[([^\]]*)\]\{[^}]*\}", r"\1", txt)
    txt = re.sub(r":sample\[([^\]]*)\]\{[^}]*\}",
                 r'<span style="font-weight:600;font-style:italic;">\1</span>', txt)
    return txt

def md_to_html(txt):
    txt = style_directives(txt)
    out, depth = [], 0
    for line in txt.split("\n"):
        indent = len(line) - len(line.lstrip())
        t = line.strip()
        m = re.match(r"[-*] (.*)", t)
        if m:
            target = indent // 4 + 1
            while depth < target: out.append("<ul style='margin-top:4px;margin-bottom:4px;'>"); depth += 1
            while depth > target: out.append("</ul>"); depth -= 1
            out.append(f"<li>{m.group(1)}</li>")
        elif t:
            while depth > 0: out.append("</ul>"); depth -= 1
            out.append(f"<p style='margin-top:4px;margin-bottom:4px;'>{t}</p>")
    while depth > 0: out.append("</ul>"); depth -= 1
    return "\n".join(out)

# HTML Table Parser Helper
class HTMLTableTextExtractor(HTMLParser):
    def __init__(self):
        super().__init__()
        self.in_table = False
        self.in_cell = False
        self.current_table = []
        self.current_row = []
        self.current_cell = []
        self.tables = []

    def handle_starttag(self, tag, attrs):
        if tag == "table":
            self.in_table = True
            self.current_table = []
        elif tag in ("td", "th") and self.in_table:
            self.in_cell = True
            self.current_cell = []
        elif tag == "tr" and self.in_table:
            self.current_row = []

    def handle_endtag(self, tag):
        if tag == "table" and self.in_table:
            self.in_table = False
            if self.current_table:
                self.tables.append(self.current_table)
        elif tag in ("td", "th") and self.in_cell:
            self.in_cell = False
            self.current_row.append(" ".join("".join(self.current_cell).split()))
        elif tag == "tr" and self.in_table:
            if self.current_row:
                self.current_table.append(self.current_row)

    def handle_data(self, data):
        if self.in_cell:
            self.current_cell.append(data)

def extract_tables_as_text(html_content):
    parser = HTMLTableTextExtractor()
    parser.feed(html_content)
    lines = []
    for idx, table in enumerate(parser.tables):
        for row in table:
            lines.append("\t".join(row))
        lines.append("")
    return "\n".join(lines)

def parse_multisample_html(html_path):
    with open(html_path, encoding="utf-8", errors="replace") as fh:
        content = fh.read()
    table_text = extract_tables_as_text(content)
    return content, table_text

def parse_rnaseq_qc(report_dir, html_path):
    txt_path = os.path.join(report_dir, "rnaseq_qc_results.txt")
    if os.path.exists(txt_path):
        with open(txt_path, encoding="utf-8", errors="replace") as fh:
            text_data = fh.read()
    else:
        with open(html_path, encoding="utf-8", errors="replace") as fh:
            text_data = extract_tables_as_text(fh.read())
    with open(html_path, encoding="utf-8", errors="replace") as fh:
        html_content = fh.read()
    return html_content, text_data

def parse_bam_qc(report_dir, html_path):
    txt_path = os.path.join(report_dir, "genome_results.txt")
    if os.path.exists(txt_path):
        with open(txt_path, encoding="utf-8", errors="replace") as fh:
            text_data = fh.read()
    else:
        with open(html_path, encoding="utf-8", errors="replace") as fh:
            text_data = extract_tables_as_text(fh.read())
    with open(html_path, encoding="utf-8", errors="replace") as fh:
        html_content = fh.read()
    return html_content, text_data

def inject_ai_box(html_content, summary_body_html, footer_html):
    # Ensure UTF-8 charset meta tag is declared in <head> so browsers do not fallback
    # to Windows-1252/ISO-8859-1 (which causes Mojibake for UTF-8 characters like 🤖, ×, –, ’ -> ðŸ¤–)
    if not re.search(r'<meta\s+charset=', html_content, re.IGNORECASE) and not re.search(r'http-equiv=["\']content-type["\']', html_content, re.IGNORECASE):
        if re.search(r'<head[^>]*>', html_content, re.IGNORECASE):
            html_content = re.sub(r'(<head[^>]*>)', r'\1\n\t<meta charset="utf-8">', html_content, count=1, flags=re.IGNORECASE)
        elif re.search(r'<html[^>]*>', html_content, re.IGNORECASE):
            html_content = re.sub(r'(<html[^>]*>)', r'\1\n<head><meta charset="utf-8"></head>', html_content, count=1, flags=re.IGNORECASE)

    box_html = (
        f'\n<div class="ai-summary-box" style="background-color: #f8f9fa; border-left: 4px solid #007bff; '
        f'padding: 12px 16px; margin: 15px 0; border-radius: 4px; font-family: sans-serif;">\n'
        f'  <h4 style="margin-top:0; margin-bottom: 8px; color: #007bff; font-weight: 600;">🤖 AI Summary</h4>\n'
        f'  <div class="ai-summary-content" style="font-size: 0.95em; color: #333;">\n{summary_body_html}\n  </div>\n'
        f'  {footer_html}\n'
        f'</div>\n'
    )

    # Check if already injected
    if 'class="ai-summary-box"' in html_content:
        return html_content

    # Inject right after Summary heading div or section
    pattern = r'(<h2[^>]*>\s*Summary\s*<.*?</h2>)'
    if re.search(pattern, html_content, re.IGNORECASE):
        return re.sub(pattern, r'\1' + box_html, html_content, count=1, flags=re.IGNORECASE)

    # Fallback 1: right after <div class="content">
    if '<div class="content">' in html_content:
        return html_content.replace('<div class="content">', '<div class="content">' + box_html, 1)

    return html_content + box_html

def ask_llm(cfg, sys_prompt, data_text):
    data_text = llm_common.cap_text(data_text, cfg.llm_context_window)
    messages = [
        {"role": "system", "content": sys_prompt},
        {"role": "user",   "content": f"Data:\n{data_text}"},
    ]
    try:
        text, usage = llm_common.chat_completion(
            cfg.llm_endpoint, cfg.llm_model, cfg.llm_api_key, messages, timeout=cfg.llm_timeout)
    except llm_common.LLMTimeout:
        raise
    except Exception as e:
        llm_common.log(f"[AI] Qualimap error: {e}")
        return "_(no AI response)_", {}
    return (text or "_(no AI response)_"), usage

MULTISAMPLE_SECTION_MAP = {
    "Coverage across reference": "Coverage Across Reference (Mean/Std Coverage per sample)",
    "Coverage Histogram": "Coverage Histogram & Distribution per sample",
    "Genome Fraction Coverage": "Genome Fraction Coverage across samples",
    "Duplication Rate Histogram": "Duplication Rate Histogram across samples",
    "Mapped reads GC-content": "Mapped Reads GC-content (GC % per sample)",
    "Mapped Reads GC-content Distribution": "Mapped Reads GC-content Distribution per sample",
    "Mapping Quality Across Reference": "Mapping Quality Across Reference (Mapping Quality Mean per sample)",
    "Mapping Quality Histogram": "Mapping Quality Histogram per sample",
    "Insert Size Across Reference": "Insert Size Across Reference (Insert Size Median per sample)",
    "Insert Size Histogram": "Insert Size Histogram per sample",
    "PCA": "PCA Plot of sample QC metrics",
}

def process_multisample_report(cfg, html_path):
    llm_common.log(f"[Qualimap AI] Annotating multi-sample report: {html_path}")
    html_content, table_text = parse_multisample_html(html_path)
    if not table_text.strip():
        llm_common.log(f"[Qualimap AI] Warning: No table data found in {html_path}")
        return

    text, usage = ask_llm(cfg, SYS_PROMPT_MULTISAMPLE, table_text)
    if llm_common.is_degraded(text):
        llm_common.log(f"[Qualimap AI] Degraded response dropped for {html_path}")
        return

    summary_html = md_to_html(text)
    footer = ai_footer(cfg, usage, data_filename="multibamqc_results")
    html_content = inject_ai_box(html_content, summary_html, footer)

    # Process per-section AI summaries for multi-sample report
    for heading, metric_desc in MULTISAMPLE_SECTION_MAP.items():
        if re.search(r'<h2[^>]*>\s*' + re.escape(heading) + r'[^>]*>', html_content, re.IGNORECASE):
            try:
                sec_prompt = f"{SYS_PROMPT_SECTION}\nSection: {heading}\nMetric focus: {metric_desc}"
                sec_text, sec_usage = ask_llm(cfg, sec_prompt, table_text)
                if not llm_common.is_degraded(sec_text):
                    sec_body_html = md_to_html(sec_text)
                    sec_footer = ai_footer(cfg, sec_usage, data_filename=f"multibamqc_{heading.lower().replace(' ', '_')}")
                    html_content = inject_section_ai_box(html_content, heading, sec_body_html, sec_footer)
            except Exception as e:
                llm_common.log(f"[Qualimap AI] Section {heading} error for multi-sample report: {e}")

    with open(html_path, "w", encoding="utf-8") as fh:
        fh.write(html_content)
    llm_common.log(f"[Qualimap AI] Done multi-sample report: {html_path}")

SECTION_MAP = {
    # BAM QC raw data files -> HTML section heading names
    "coverage_across_reference.txt": "Coverage across reference",
    "coverage_histogram.txt": "Coverage Histogram",
    "duplication_rate_histogram.txt": "Duplication Rate Histogram",
    "genome_fraction_coverage.txt": "Genome Fraction Coverage",
    "homopolymer_indels.txt": "Homopolymer Indels",
    "mapped_reads_clipping_profile.txt": "Mapped Reads Clipping Profile",
    "mapped_reads_gc-content_distribution.txt": "Mapped Reads GC-content Distribution",
    "mapped_reads_nucleotide_content.txt": "Mapped Reads Nucleotide Content",
    "mapping_quality_across_reference.txt": "Mapping Quality Across Reference",
    "mapping_quality_histogram.txt": "Mapping Quality Histogram",

    # RNA-Seq QC raw data files -> HTML section heading names
    "coverage_profile_along_genes_(total).txt": "Coverage Profile Along Genes (Total)",
    "coverage_profile_along_genes_(low).txt": "Coverage Profile Along Genes (Low)",
    "coverage_profile_along_genes_(high).txt": "Coverage Profile Along Genes (High)",
}

SYS_PROMPT_SECTION = "\n".join([
    "You are an expert bioinformatician evaluating a specific plot/section of a Qualimap report.",
    "Produce 1-2 concise bullet points summarizing key observations from the provided plot raw data.",
    "Use markdown. Highlight severity with directives like :span[value]{.text-red}, .text-orange, .text-yellow, .text-green if applicable.",
])

def inject_section_ai_box(html_content, heading_name, summary_body_html, footer_html):
    box_html = (
        f'\n<div class="ai-summary-box-section" style="background-color: #f8f9fa; border-left: 3px solid #17a2b8; '
        f'padding: 8px 12px; margin: 10px 0; border-radius: 4px; font-family: sans-serif; font-size: 0.9em;">\n'
        f'  <div class="ai-summary-content" style="color: #333;">\n{summary_body_html}\n  </div>\n'
        f'  {footer_html}\n'
        f'</div>\n'
    )
    pattern = r'(<h2[^>]*>\s*' + re.escape(heading_name) + r'[^>]*>.*?</h2>)'
    match = re.search(pattern, html_content, re.IGNORECASE)
    if match:
        snippet_after = html_content[match.end():match.end()+250]
        if 'ai-summary-box' in snippet_after or 'ai-summary-box-section' in snippet_after:
            return html_content
        return re.sub(pattern, r'\1' + box_html, html_content, count=1, flags=re.IGNORECASE)
    return html_content

def process_single_sample_report(cfg, html_path, report_type):
    report_dir = os.path.dirname(html_path)
    sample_name = os.path.basename(report_dir)
    llm_common.log(f"[Qualimap AI] Annotating {report_type} report for {sample_name}: {html_path}")

    if report_type == "rnaseq":
        html_content, text_data = parse_rnaseq_qc(report_dir, html_path)
        sys_prompt = SYS_PROMPT_RNASEQ
        parsed_name = "rnaseq_qc_results.txt"
    else:
        html_content, text_data = parse_bam_qc(report_dir, html_path)
        sys_prompt = SYS_PROMPT_BAMQC
        parsed_name = "genome_results.txt"

    if not text_data.strip():
        llm_common.log(f"[Qualimap AI] Warning: No text data for {sample_name}")
        return

    text, usage = ask_llm(cfg, sys_prompt, text_data)
    if llm_common.is_degraded(text):
        llm_common.log(f"[Qualimap AI] Degraded response dropped for {sample_name}")
        return

    summary_html = md_to_html(text)
    footer = ai_footer(cfg, usage, data_filename=parsed_name)
    html_content = inject_ai_box(html_content, summary_html, footer)

    # Process per-section raw data tables from raw_data_qualimapReport directory
    raw_data_dir = os.path.join(report_dir, "raw_data_qualimapReport")
    if os.path.isdir(raw_data_dir):
        for fname, heading in SECTION_MAP.items():
            fpath = os.path.join(raw_data_dir, fname)
            if not os.path.exists(fpath):
                continue
            try:
                with open(fpath, encoding="utf-8", errors="replace") as fh:
                    raw_text = fh.read().strip()
                if not raw_text:
                    continue
                # Cap large raw histogram files (e.g. coverage_histogram.txt 400KB+) to max 100 lines
                lines = [l for l in raw_text.splitlines() if l.strip()]
                if len(lines) > 100:
                    raw_text = "\n".join(lines[:50] + ["\n... [middle histogram data points omitted] ...\n"] + lines[-50:])
                sec_text, sec_usage = ask_llm(cfg, f"{SYS_PROMPT_SECTION}\nSection: {heading}\nSample: {sample_name}", raw_text)
                if not llm_common.is_degraded(sec_text):
                    sec_body_html = md_to_html(sec_text)
                    sec_footer = ai_footer(cfg, sec_usage, data_filename=fname)
                    html_content = inject_section_ai_box(html_content, heading, sec_body_html, sec_footer)
            except Exception as e:
                llm_common.log(f"[Qualimap AI] Section {fname} error for {sample_name}: {e}")

    with open(html_path, "w", encoding="utf-8") as fh:
        fh.write(html_content)
    llm_common.log(f"[Qualimap AI] Done {sample_name}")

def main():
    p = argparse.ArgumentParser(description="Qualimap AI annotation script.")
    p.add_argument("--analysis-dir", required=True, help="Root directory containing Qualimap reports.")
    p.add_argument("--llm-endpoint", default=DEF_ENDPOINT, help="OpenAI-compatible URL")
    p.add_argument("--llm-model", default=DEF_MODEL, help="Model name")
    p.add_argument("--llm-api-key", default=DEF_API_KEY, help="API key")
    p.add_argument("--llm-context-window", type=int, default=DEF_CONTEXT_WINDOW)
    p.add_argument("--llm-timeout", type=int, default=DEF_TIMEOUT)
    args = p.parse_args()

    if not args.llm_endpoint or not args.llm_model:
        llm_common.log("[Qualimap AI] LLM_ENDPOINT and LLM_MODEL must be supplied. Exiting without changes.")
        sys.exit(0)

    cfg = args
    analysis_dir = os.path.abspath(args.analysis_dir)

    multi_reports = []
    single_rnaseq_reports = []
    single_bam_reports = []

    for root, dirs, files in os.walk(analysis_dir):
        for f in files:
            full = os.path.join(root, f)
            if f == "multisampleBamQcReport.html":
                multi_reports.append(full)
            elif f == "qualimapReport.html":
                root_low = root.lower()
                if os.path.exists(os.path.join(root, "rnaseq_qc_results.txt")) or "rnaseq" in root_low:
                    single_rnaseq_reports.append(full)
                elif os.path.exists(os.path.join(root, "genome_results.txt")) or "bam" in root_low:
                    single_bam_reports.append(full)
                else:
                    single_rnaseq_reports.append(full)

    secrets = llm_common.secret_values(endpoint=cfg.llm_endpoint, api_key=cfg.llm_api_key)

    try:
        # Process Multi-sample report first
        for m_rep in multi_reports:
            try:
                process_multisample_report(cfg, m_rep)
                llm_common.scrub_file(m_rep, secrets)
            except llm_common.LLMTimeout:
                llm_common.log(f"[Qualimap AI] Timeout processing {m_rep}")

        # Process single-sample RNA-Seq reports
        for r_rep in single_rnaseq_reports:
            try:
                process_single_sample_report(cfg, r_rep, "rnaseq")
                llm_common.scrub_file(r_rep, secrets)
            except llm_common.LLMTimeout:
                llm_common.log(f"[Qualimap AI] Timeout processing {r_rep}")

        # Process single-sample BAM reports
        for b_rep in single_bam_reports:
            try:
                process_single_sample_report(cfg, b_rep, "bamqc")
                llm_common.scrub_file(b_rep, secrets)
            except llm_common.LLMTimeout:
                llm_common.log(f"[Qualimap AI] Timeout processing {b_rep}")

    except Exception as e:
        llm_common.log(f"[Qualimap AI] Error during AI pass: {e}")

if __name__ == "__main__":
    main()
